name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node scripts/prisma-env.mjs generate"
dev = "node scripts/prisma-env.mjs migrate && node scripts/prisma-env.mjs exec npm exec react-router dev"
