ALTER TABLE "CampaignDesign" ADD COLUMN "timerNumberFontSize" INTEGER NOT NULL DEFAULT 38;
ALTER TABLE "CampaignDesign" ADD COLUMN "timerLabelFontSize" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "CampaignDesign" ADD COLUMN "timerGap" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "CampaignDesign" ADD COLUMN "timerUnitGap" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "CampaignDesign" ADD COLUMN "timerPaddingBlock" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "CampaignDesign" ADD COLUMN "timerPaddingInline" INTEGER NOT NULL DEFAULT 12;
