#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const rootDir = process.cwd();
const prismaDir = path.join(rootDir, "prisma");
const baseSchemaPath = path.join(prismaDir, "schema.prisma");
const sqliteSchemaPath = path.join(prismaDir, "schema.sqlite.generated.prisma");
const envFile = readEnvFile(path.join(rootDir, ".env"));

const appEnv = process.env.APP_ENV || envFile.APP_ENV || "";
const nodeEnv = process.env.NODE_ENV || envFile.NODE_ENV || "";
const envIsDevelopment = appEnv === "development" || nodeEnv === "development";
const hasExplicitDatabaseUrl =
  Object.prototype.hasOwnProperty.call(process.env, "DATABASE_URL") &&
  Boolean(process.env.DATABASE_URL);
const developmentDatabaseUrl =
  process.env.DEVELOPMENT_DATABASE_URL ||
  envFile.DEVELOPMENT_DATABASE_URL ||
  "file:./dev.sqlite";

const databaseUrl = resolveDatabaseUrl();
const provider = isSqliteUrl(databaseUrl) ? "sqlite" : "postgresql";
const schemaPath =
  provider === "sqlite" ? ensureSqliteSchema() : baseSchemaPath;
const command = process.argv[2] || "setup";
const forwardedArgs = process.argv.slice(3);

switch (command) {
  case "generate":
    runPrisma(["generate", "--schema", schemaPath]);
    break;
  case "migrate":
    if (provider === "sqlite") {
      runPrisma(["db", "push", "--schema", schemaPath, "--skip-generate"]);
    } else {
      runPrisma(["migrate", "deploy", "--schema", schemaPath]);
    }
    break;
  case "setup":
    runPrisma(["generate", "--schema", schemaPath]);
    if (provider === "sqlite") {
      runPrisma(["db", "push", "--schema", schemaPath, "--skip-generate"]);
    } else {
      runPrisma(["migrate", "deploy", "--schema", schemaPath]);
    }
    break;
  case "exec":
    if (forwardedArgs.length === 0) {
      fail("Usage: node scripts/prisma-env.mjs exec <command> [...args]");
    }
    run(forwardedArgs[0], forwardedArgs.slice(1));
    break;
  default:
    fail(
      `Unknown command "${command}". Use generate, migrate, setup, or exec.`,
    );
}

function resolveDatabaseUrl() {
  if (hasExplicitDatabaseUrl) {
    return process.env.DATABASE_URL;
  }

  if (envIsDevelopment) {
    return developmentDatabaseUrl;
  }

  const configuredDatabaseUrl = envFile.DATABASE_URL;
  if (configuredDatabaseUrl) {
    return configuredDatabaseUrl;
  }

  fail(
    "DATABASE_URL is required outside development. Set DATABASE_URL or APP_ENV=development.",
  );
}

function ensureSqliteSchema() {
  const schema = fs.readFileSync(baseSchemaPath, "utf8");
  const sqliteSchema = schema.replace(
    /provider\s*=\s*"postgresql"/,
    'provider = "sqlite"',
  );

  if (sqliteSchema === schema) {
    fail("Could not create SQLite Prisma schema from prisma/schema.prisma.");
  }

  fs.writeFileSync(
    sqliteSchemaPath,
    [
      "// Generated by scripts/prisma-env.mjs for development SQLite.",
      "// Do not edit this file directly.",
      sqliteSchema,
    ].join("\n"),
  );

  return sqliteSchemaPath;
}

function runPrisma(args) {
  run("npm", ["exec", "prisma", "--", ...args]);
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    env: {
      ...process.env,
      DATABASE_URL: databaseUrl,
      ...(appEnv ? { APP_ENV: appEnv } : {}),
      ...(nodeEnv ? { NODE_ENV: nodeEnv } : {}),
    },
    stdio: "inherit",
    shell: false,
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function isSqliteUrl(url) {
  return url.startsWith("file:") || url.startsWith("sqlite:");
}

function readEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  return Object.fromEntries(
    fs
      .readFileSync(filePath, "utf8")
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#"))
      .map((line) => {
        const separatorIndex = line.indexOf("=");

        if (separatorIndex === -1) return null;

        const key = line.slice(0, separatorIndex).trim();
        const value = line
          .slice(separatorIndex + 1)
          .trim()
          .replace(/^['"]|['"]$/g, "");

        return key ? [key, value] : null;
      })
      .filter(Boolean),
  );
}

function fail(message) {
  console.error(message);
  process.exit(1);
}
